deleted old code

diff --git a/sync-united b/sync-united
--- a/sync-united
+++ b/sync-united
@@ -107,6 +107,13 @@ rsync -rav -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" 
 # rsync -av --ignore-existing x86_64/ ${user}@frs.sourceforge.net:/home/frs/project/unitedrpms/${task}/x86_64/
 rsync -rav -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete . ${user}@frs.sourceforge.net:/home/frs/project/unitedrpms/${task}/
 
+if [[ $? -gt 0 ]]; then
+echo 'Done rsync succes'
+else
+echo 'ERROR rsymc failed'
+exit 1
+fi
+
 popd
 }
 
